use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# FechgoWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :fechgo, FechgoWeb.Endpoint,
  load_from_system_env: true,
  url: [host: "fechgo.cl", port: System.get_env("FECHGO_PORT")],
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true

# Do not print debug messages in production
config :logger, level: :info

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :fechgo, FechgoWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [:inet6,
#               port: 443,
#               keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#               certfile: System.get_env("SOME_APP_SSL_CERT_PATH")]
#
# Where those two env variables return an absolute path to
# the key and cert in disk or a relative path inside priv,
# for example "priv/ssl/server.key".
#
# We also recommend setting `force_ssl`, ensuring no data is
# ever sent via http, always redirecting to https:
#
#     config :fechgo, FechgoWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :fechgo, FechgoWeb.Endpoint, server: true
#

config :fechgo, Fechgo.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: System.get_env("FECHGO_DB_USERNAME"),
  password: System.get_env("FECHGO_DB_PASSWORD"),
  database: System.get_env("FECHGO_DB_NAME"),
  hostname: System.get_env("FECHGO_DB_HOST"),
  pool_size: 25

config :fechgo,
  uploads_path: System.get_env("FECHGO_UPLOADS_PATH")

config :upload, Upload,
  adapter: Upload.Adapters.Local

config :upload, Upload.Adapters.Local,
  storage_path: System.get_env("FECHGO_UPLOADS_PATH"),
  public_path: "/uploads"
